---
extends: default

rules:
  line-length:
    max: 300
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  trailing-spaces: enable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on']
    check-keys: false
