services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscvrat-hugo
    ports:
      - "1313:1313"
    volumes:
      - ./website:/src
    working_dir: /src
    environment:
      - HUGO_ENV=development
