services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscvrat-hugo
    ports:
      - "1313:1313"
    volumes:
      - ./website:/src
    working_dir: /src
    command: server --bind 0.0.0.0 --poll 3s
    environment:
      - HUGO_ENV=development
